from abc import ABC, abstractmethod

class IPropertyRepo(ABC):
    @abstractmethod
    def get(self, prop_id: int): ...
    @abstractmethod
    def add(self, prop): ...
    @abstractmethod
    def save(self, prop): ...
    @abstractmethod
    def list_approved(self, **filters): ...
