"""Remove lat and lng from properties

Revision ID: 10390a4b1a1b
Revises: 67d7b01a0301
Create Date: 2025-09-30 22:33:20.068834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10390a4b1a1b'
down_revision = '67d7b01a0301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
