"""add review report and management system

Revision ID: 129a47ccc66e
Revises: 8d7a7774ce7e
Create Date: 2025-10-15 05:25:49.278385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129a47ccc66e'
down_revision = '8d7a7774ce7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- vvv ส่วนที่แก้ไข vvv ---
    # Create the new table for review reports first
    op.create_table('review_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('review_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
        sa.Column('admin_note', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Use batch mode to alter the existing 'reviews' table
    # This is the key part to fix the SQLite error
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        # Add the new column with a server_default value.
        # This tells the database to fill existing rows with 'False' (0).
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # --- ^^^ สิ้นสุดการแก้ไข ^^^ ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- vvv ส่วนที่แก้ไข vvv ---
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    op.drop_table('review_reports')
    # --- ^^^ สิ้นสุดการแก้ไข ^^^ ---
    
    # ### end Alembic commands ###