"""final schema update for search fields

Revision ID: 158538de58c3
Revises: b2c3d4e5f6a7
Create Date: 2025-10-13 19:11:57.338800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '158538de58c3'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenities')
    op.drop_table('audit_logs')
    op.drop_table('property_images')
    op.drop_table('properties')
    op.drop_table('approval_requests')
    op.drop_table('property_amenities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_amenities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('amenity_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'amenity_id', name='uq_property_amenity')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('road', sa.VARCHAR(length=255), nullable=True),
    sa.Column('soi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('dorm_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('line_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('facebook_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rent_price', sa.INTEGER(), nullable=True),
    sa.Column('water_rate', sa.FLOAT(), nullable=True),
    sa.Column('electric_rate', sa.FLOAT(), nullable=True),
    sa.Column('deposit_amount', sa.INTEGER(), nullable=True),
    sa.Column('availability_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('workflow_status', sa.VARCHAR(length=16), nullable=True),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('location_pin', sqlite.JSON(), nullable=True),
    sa.Column('additional_info', sa.TEXT(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('actor_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=64), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('label_th', sa.VARCHAR(length=120), nullable=False),
    sa.Column('label_en', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###
