"""Add additional_info to Property table

Revision ID: 223517f90a7a
Revises: ddcffaefff55
Create Date: 2025-10-01 15:07:30.770829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223517f90a7a'
down_revision = 'ddcffaefff55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
