"""add street column to properties

Revision ID: 80d75a7f10a1
Revises: ec1e716e21d7
Create Date: 2025-10-01 02:01:56.834871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d75a7f10a1'
down_revision = 'ec1e716e21d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('street')

    # ### end Alembic commands ###
