"""separate road and soi columns in properties

Revision ID: ddcffaefff55
Revises: 80d75a7f10a1
Create Date: 2025-10-01 02:06:06.976097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcffaefff55'
down_revision = '80d75a7f10a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('road', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('soi', sa.String(length=255), nullable=True))
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('soi')
        batch_op.drop_column('road')

    # ### end Alembic commands ###
