"""Add location_pin json column to properties

Revision ID: ec1e716e21d7
Revises: 10390a4b1a1b
Create Date: 2025-09-30 22:58:45.539417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1e716e21d7'
down_revision = '10390a4b1a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_pin', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('location_pin')

    # ### end Alembic commands ###
