"""add approval status to owners table

Revision ID: f2a9b7a1c8d3
Revises: 223517f90a7a # <--- ให้แก้เป็น ID ของ migration ล่าสุดของคุณ
Create Date: 2025-10-03 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a9b7a1c8d3'
down_revision = '223517f90a7a' # <--- ให้แก้เป็น ID ของ migration ล่าสุดของคุณ
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=16), nullable=False, server_default='pending'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.false())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               server_default=sa.true())
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###