from typing import Protocol, Optional, Sequence
from app.models.property import Property


class IPropertyRepo(Protocol):
    def get(self, prop_id: int) -> Optional[Property]: ...
    def add(self, prop: Property) -> Property: ...
    def save(self, prop: Property) -> None: ...
    def list_approved(self, **filters) -> Sequence[Property]: ...