from typing import Protocol, Optional
from app.models.user import Owner, Admin


class IUserRepo(Protocol):
    def get_owner_by_email(self, email: str) -> Optional[Owner]: ...
    def add_owner(self, owner: Owner) -> Owner: ...
    def get_admin_by_username(self, username: str) -> Optional[Admin]: ...